packaging_format = 2

id = "privatebin"
name = "PrivateBin"
description.en = "Minimalist pastebin where the server has zero knowledge of pasted data"
description.fr = "Pastebin minimaliste où le serveur n'a aucune connaissance des données copiées"

version = "1.7.1~ynh1"

maintainers = [""]

[upstream]
license = "Zlib"
website = "https://privatebin.info/"
demo = "https://privatebin.net/"
admindoc = "https://github.com/PrivateBin/PrivateBin/wiki"
code = "https://github.com/PrivateBin/PrivateBin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/privatebin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/PrivateBin/PrivateBin/archive/refs/tags/1.7.1.tar.gz"
        sha256 = "136faa5ba0c2d51ace916a2c0b282f5c7d5376265406040c91730e28233367ff"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-fpm"
    