packaging_format = 2

id = "privatebin"
name = "PrivateBin"
description.en = "Pastebin where the server has zero knowledge of pasted data"
description.fr = "Pastebin où le serveur ignore les données copiées"

version = "2.0.0~ynh1"

maintainers = []

[upstream]
license = "Zlib"
website = "https://privatebin.info/"
demo = "https://privatebin.net/"
admindoc = "https://github.com/PrivateBin/PrivateBin/wiki"
code = "https://github.com/PrivateBin/PrivateBin"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/privatebin"

    [install.init_main_permission]
    help.en = "If private, only YunoHost users can create a paste, but everyone can read it."
    help.fr = "Si privé, seul les utilisateurs YunoHost peuvent créer un paste, mais tout le monde peut lire."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de", "en", "es","fr", "it", "nl", "pl", "pt"]
    default = "fr"

[resources]
        [resources.sources.main]
        url = "https://github.com/PrivateBin/PrivateBin/archive/refs/tags/2.0.0.tar.gz"
        sha256 = "4bd2ae9e560f72510f1af19dd3d062872c26bbce7cb5437cbb1f7997b83011a8"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    
    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, php8.4-gd, zlib1g-dev"

    [resources.database]
    type = "postgresql"
    