test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.8ce6cac57048e5df294269989c2432d67bef4c5c.name = "Upgrade from #1"