#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_memory_limit --value=50M
ynh_app_setting_set --key=php_upload_max_filesize --value=10M
ynh_app_setting_set --key=expire --value="1week"
ynh_app_setting_set --key=fileupload --value="false"
ynh_app_setting_set --key=template --value="bootstrap-dark"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="conf.php" --destination="$install_dir/cfg/conf.php"

chmod 600 "$install_dir/cfg/conf.php"
chown "$app:$app" "$install_dir/cfg/conf.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
