#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=php_upload_max_filesize --value=10M
ynh_app_setting_set_default --key=php_memory_limit --value=50M
ynh_app_setting_set_default --key=expire --value="1week"

# If language doesn't exist, create it
ynh_app_setting_set_default --key=language --value="fr"

if ynh_app_upgrading_from_version_before 1.7.5~ynh2; then
    ynh_script_progression "Moving data..."
    mv $install_dir/data/* $data_dir/
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="conf.php"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="conf.php" --destination="$install_dir/cfg/conf.php"

chmod 600 "$install_dir/cfg/conf.php"
chown "$app:$app" "$install_dir/cfg/conf.php"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
